### ISSUE TITLE
Schema migration doesn't work

### ISSUE THREAD

**Issue by ventsyv** [Logflare/logflare#1714]
When I run the following docker compose, I get an error that no schema has been selected. Here is the error:
```
supabase-analytics  | 13:50:57.012 [info] Starting migration
db_service      | 172.24.0.3 2023-09-29 13:50:57.152 UTC [47] postgres@postgres ERROR:  no schema has been selected to create in at character 28
db_service      | 172.24.0.3 2023-09-29 13:50:57.152 UTC [47] postgres@postgres STATEMENT:  CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" bigint, "inserted_at" timestamp(0), PRIMARY KEY ("version"))
supabase-analytics  | 13:50:57.163 [error] Could not create schema migrations table. This error usually happens due to the following:
supabase-analytics  | 
supabase-analytics  |   * The database does not exist
supabase-analytics  |   * The "schema_migrations" table, which Ecto uses for managing
supabase-analytics  |     migrations, was defined by another library
supabase-analytics  |   * There is a deadlock while migrating (such as using concurrent
supabase-analytics  |     indexes with a migration_lock)
supabase-analytics  | 

```
If I disable the DB_SCHEMA and POSTGRES_BACKEND_SCHEMA variable the migration works fine in the current schema.

```
version: '3.4'

services:
  db:
    image: supabase/postgres:15.1.0.121
    container_name: "kos_db_service"
    env_file: .env
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -h ${POSTGRES_HOST}
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 10
    restart: unless-stopped
    ports:
      # Pass down internal port because it's set dynamically by other services
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - my_dev_net
    volumes:
      - /var/kos/db/volumes/db/realtime.sql:/docker-entrypoint-initdb.d/migrations/99-realtime.sql:Z
      # Must be superuser to create event trigger
      - /var/kos/db/volumes/db/webhooks.sql:/docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql:Z
      # Must be superuser to alter reserved role
      - /var/kos/db/volumes/db/roles.sql:/docker-entrypoint-initdb.d/init-scripts/99-roles.sql:Z
      # PGDATA directory is persisted between restarts
      - /var/kos/db/volumes/db/data:/var/lib/postgresql/data:Z
      # Changes required for Analytics support
      - /var/kos/db/volumes/db/logs.sql:/docker-entrypoint-initdb.d/migrations/99-logs.sql:Z
  analytics:
    container_name: supabase-analytics
    image: supabase/logflare:latest
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:${LOGFLARE_PORT}/health" ]
      timeout: 5s
      interval: 5s
      retries: 10
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file: .env  
    environment:
      LOGFLARE_NODE_HOST:  127.0.0.1
      DB_USERNAME: ${POSTGRES_USER}
      DB_DATABASE: ${MY_DB_NAME}
      DB_HOSTNAME: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      #DB_SCHEMA: _analytics
      LOGFLARE_API_KEY: ${LOGFLARE_API_KEY}
      LOGFLARE_SINGLE_TENANT: true
      LOGFLARE_SUPABASE_MODE: true
      LOGFLARE_MIN_CLUSTER_SIZE: 1
      RELEASE_COOKIE: cookie

      # Comment variables to use Big Query backend for analytics
      POSTGRES_BACKEND_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${MY_DB_NAME}
      #POSTGRES_BACKEND_SCHEMA: _analytics
      LOGFLARE_FEATURE_FLAG_OVERRIDE: multibackend=true

      # Uncomment to use Big Query backend for analytics
      # GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      # GOOGLE_PROJECT_NUMBER: ${GOOGLE_PROJECT_NUMBER}
    ports:
      - ${LOGFLARE_PORT}:${LOGFLARE_PORT}
    networks:
      - my_dev_net
    volumes:
      - type: bind
        source: ${PWD}/.env
        target: /tmp/.secrets.env
        read_only: true

networks:
  my_dev_net:
    external: true 
volumes:
  kos_db_volume:
    external: true
```

I don't see the schema being created in the DB container. My docker compose is pretty much a copy of https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml 
Am I missing something or is this a bug?
