### ISSUE TITLE
No changes in logs when setting log level to debug (supabase/logflare:1.5.8)

### ISSUE THREAD

**Issue by sabman** [Logflare/logflare#1871]
In the 1.5.8 version of Logflare, setting the log level to "debug" does not change or affect the logs' output. This issue is preventing detailed debugging information from being displayed.

**Expected Behavior:**
On setting the log level to "debug", the logs should display more detailed and verbose information, aiding in debugging processes.

**Actual Behavior:**
Despite setting the log level to "debug", the logs' output remains unchanged, showing the same level of detail as before.

**Steps to Reproduce:**

1. Ensure Logflare is updated to the latest version.
2. Set the log level to "debug".
3. Check the logs for any changes in output detail.

**My setup:**

I have the following docker config for the logflare service:

```yml
analytics:
  container_name: supabase-analytics
  image: supabase/logflare:1.5.8
  healthcheck:
    test: [ "CMD", "curl", "http://localhost:4000/health" ]
    timeout: 5s
    interval: 5s
    retries: 10
  restart: unless-stopped
  depends_on:
    db:
      # Disable this if you are using an external Postgres database
      condition: service_healthy
  # Uncomment to use Big Query backend for analytics
  volumes:
    - type: bind
      source: ./volumes/logflare/key.json
      target: /opt/app/rel/logflare/bin/gcloud.json
      read_only: true
  ports:
    - 4000:4000
  environment:
    PORT: 4000
    LOGFLARE_NODE_HOST:  127.0.0.1
    DB_USERNAME: supabase_admin
    DB_DATABASE: ${POSTGRES_DB}
    DB_HOSTNAME: ${POSTGRES_HOST}
    DB_PORT: ${POSTGRES_PORT}
    DB_PASSWORD: ${POSTGRES_PASSWORD}
    DB_SCHEMA: _analytics
    LOGFLARE_API_KEY: ${LOGFLARE_API_KEY}
    LOGFLARE_SINGLE_TENANT: true
    LOGFLARE_SUPABASE_MODE: true
    LOGFLARE_MIN_CLUSTER_SIZE: 1
    RELEASE_COOKIE: cookie
    LOGFLARE_LOG_LEVEL: "debug"

    # Comment variables to use Big Query backend for analytics
     POSTGRES_BACKEND_URL: postgresql://supabase_admin:${POSTGRES_PASSWORD}TGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
     POSTGRES_BACKEND_SCHEMA: _analytics
     LOGFLARE_FEATURE_FLAG_OVERRIDE: multibackend=true

    # Uncomment to use Big Query backend for analytics
    GOOGLE_PROJECT_ID: my-custom-proj-85
    GOOGLE_PROJECT_NUMBER: 504895627183
  entrypoint: |
                sh -c `cat <<'EOF' > run.sh && sh run.sh
                ./logflare eval Logflare.Release.migrate
                ./logflare start --sname logflare
                EOF
                `
```
